name: Daily Update of the Registry

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  update-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - run: npm ci
      - run: npm test

      - run: npm run-script update
      - run: npm run-script normalize
      - run: npm run-script flatten
      - run: npm run-script did_document ${{ secrets.SIGNER_PRIVATE_KEY }}
      - run: npm test

      - uses: peter-evans/create-pull-request@v3.10.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer: GitHub <noreply@github.com>
          commit-message: Registry updates for ${{ steps.date.outputs.date }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Registry updates for ${{ steps.date.outputs.date }}
          body: Auto-created Pull Request
          branch: update-registry-${{ steps.date.outputs.date }}
          delete-branch: true
          labels: |
            report
            automated pr
          assignees: vitorpamplona
          reviewers: vitorpamplona
