name: Daily Update of the Registry. 

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

#on:
#  schedule:
#    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

      - name: Create a Branch for Today's changes
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: update-regisry-${{ steps.date.outputs.date }}

      - run: npm run-script update
      - run: npm test

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub AutoUpdater
          author_email: github@pathcheck.org
          message: Registry updates for ${{ steps.date.outputs.date }}

      - uses: peter-evans/create-pull-request@v3.10.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Registry updates for ${{ steps.date.outputs.date }}
          title: Registry updates for ${{ steps.date.outputs.date }}
          body: Auto-created Pull Request
          branch: main 
          base: update-regisry-${{ steps.date.outputs.date }} 
